# Generated by Django 2.2 on 2024-11-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0004_auto_20241106_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('customer_id', models.IntegerField()),
                ('cash_balance', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('transaction_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='customer.Customer')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='restaurant.MenuItem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='restaurant.Restaurant')),
            ],
            options={
                'db_table': 'purchase_histories',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='customers_name_25d5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['customer', 'menu', 'restaurant'], name='purchase_hi_custome_1b413d_idx'),
        ),
    ]
