# Generated by Django 2.2 on 2024-11-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20241106_1109'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menuitem',
            table='restaurant_menu_items',
        ),
        migrations.AlterModelTable(
            name='openinghour',
            table='restaurant_opening_hours',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurants',
        ),
    ]
