# Generated by Django 2.2 on 2024-11-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20241106_1111'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['name'], name='restaurant__name_b655f0_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name'], name='restaurants_name_cc4837_idx'),
        ),
    ]
